
default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  adapter: postgresql
  encoding: unicode
  database: friendsClub_development
  username: postgres
  password: Miwa7355608
  host: localhost
  port: 5432
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: friendsClub_test
  username: postgres
  password: Miwa7355608
  host: localhost


production:
  <<: *default
  database: friendsClub_production
  username: friendsClub
  password: <%= ENV["FRIENDSCLUB_DATABASE_PASSWORD"] %>
